manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: mine
      url-base: https://github.com/NoRyyZ
  projects:
    - name: zmk-dula-encoder
      remote: mine
      revision: main
      import: app/west.yml
  self:
    path: config
